---
apiVersion: v1
kind: ConfigMap
metadata:
  name: news-sentiment
  namespace: rwml
data:
  # Quote them!!! - by Marius
  # https://12factor.net/config
  KAFKA_BROKER_ADDRESS: "kafka-e11b-kafka-bootstrap.kafka.svc.cluster.local:9092"
  KAFKA_INPUT_TOPIC: "news"
  KAFKA_OUTPUT_TOPIC: "news-sentiment"
  KAFKA_CONSUMER_GROUP: "news_sentiment_consumer_group_5"
  MODEL: "openai-generic/deepseek-r1:8b"
  BASE_URL: "http://192.168.1.3:8080/v1"