---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-sentiment
  labels:
    app.kubernetes.io/name: news-sentiment # This is the name the Service looks for
  namespace: rwml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: news-sentiment
  template:
    metadata:
      labels:
        app: news-sentiment
    spec:
      containers:
      - name: news-sentiment
        image: news-sentiment:dev
        imagePullPolicy: Never # Use the local image
        env:
        - name: KAFKA_BROKER_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: news-sentiment
              key: KAFKA_BROKER_ADDRESS
        - name: KAFKA_INPUT_TOPIC
          valueFrom:
            configMapKeyRef:
              name: news-sentiment
              key: KAFKA_INPUT_TOPIC
        - name: KAFKA_OUTPUT_TOPIC
          valueFrom:
            configMapKeyRef:
              name: news-sentiment
              key: KAFKA_OUTPUT_TOPIC
        - name: KAFKA_CONSUMER_GROUP
          valueFrom:
            configMapKeyRef:
              name: news-sentiment
              key: KAFKA_CONSUMER_GROUP
        - name: MODEL
          valueFrom:
            configMapKeyRef:
              name: news-sentiment
              key: MODEL
        - name: BASE_URL
          valueFrom:
            configMapKeyRef:
              name: news-sentiment
              key: BASE_URL