---
apiVersion: v1
kind: ConfigMap
metadata:
  name: training-pipeline
  namespace: rwml
data:
  # Quote them!!! - by Marius
  # https://12factor.net/config
  MLFLOW_TRACKING_URI: "http://mlflow-tracking.mlflow.svc.cluster.local:80"
  MLFLOW_TRACKING_USERNAME: "user"
  MLFLOW_TRACKING_PASSWORD: "6440921D-2493-42AA-BE40-428CD753D81D"
  RISINGWAVE_HOST: "risingwave.risingwave.svc.cluster.local"
  RISINGWAVE_PORT: "4567"
  RISINGWAVE_USER: "root"
  RISINGWAVE_PASSWORD: ""
  RISINGWAVE_DATABASE: "dev"
  RISINGWAVE_TABLE: "public.technical_indicators"
  PAIR: "BTC/USD"
  TRAINING_DATA_HORIZON_DAYS: "60"
  CANDLE_SECONDS: "60"
  PREDICTION_HORIZON_SECONDS: "300"
  TRAIN_TEST_SPLIT_RATIO: "0.8"
  MAX_PERCENTAGE_ROWS_WITH_MISSING_VALUES: "0.01"
  DATA_PROFILING_N_ROWS: "1"
  EDA_REPORT_HTML_PATH: "./eda_report.html"
  HYPERPARAM_SEARCH_TRIALS: "10"
  MODEL_NAME: "HuberRegressor"
  N_MODEL_CANDIDATES: "1"
  # I intentionally set a high value to ensure we keep on pushing models to the registry
  MAX_PERCENTAGE_DIFF_MAE_WRT_BASELINE: "0.1"