---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: news
  labels:
    app.kubernetes.io/name: news # This is the name the Service looks for
  namespace: rwml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: news
  template:
    metadata:
      labels:
        app: news
    spec:
      containers:
      - name: news
        image: news:dev
        imagePullPolicy: Never # Use the local image
        env:
        - name: CRYPTOPANIC_API_KEY
          valueFrom:
            configMapKeyRef:
              name: news
              key: CRYPTOPANIC_API_KEY
        - name: KAFKA_BROKER_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: news
              key: KAFKA_BROKER_ADDRESS
        - name: KAFKA_OUTPUT_TOPIC
          valueFrom:
            configMapKeyRef:
              name: news
              key: KAFKA_OUTPUT_TOPIC
